
BACKUP DATABASE NPT53_ARGABRIEL   TO DISK = '\\lulas-system001\backup2\NPT53_ARGABRIEL.Bak';
GO
BACKUP DATABASE NPT53_BALANZA     TO DISK = '\\lulas-system001\backup2\NPT53_BALANZA.Bak';  
GO
BACKUP DATABASE NPT53_DESCARGA    TO DISK = '\\lulas-system001\backup2\NPT53_DESCARGA.Bak'; 
GO
BACKUP DATABASE NPT53_EDIFACT     TO DISK = '\\lulas-system001\backup2\NPT53_EDIFACT.Bak';  
GO
BACKUP DATABASE NPT53_NEPPAITA    TO DISK = '\\lulas-system001\backup2\NPT53_NEPPAITA.Bak'; 
GO
BACKUP DATABASE NPT53_NT_WEB      TO DISK = '\\lulas-system001\backup2\NPT53_NT_WEB.Bak';   
GO
BACKUP DATABASE NPT53_NT          TO DISK = '\\lulas-system001\backup2\NPT53_NT.Bak';       
GO
BACKUP DATABASE NPT53_OCEANO      TO DISK = '\\lulas-system001\backup2\NPT53_OCEANO.Bak';   
GO
BACKUP DATABASE NPT53_ODSPAITA    TO DISK = '\\lulas-system001\backup2\NPT53_ODSPAITA.Bak'; 
GO
BACKUP DATABASE NPT53_PAITA       TO DISK = '\\lulas-system001\backup2\NPT53_PAITA.Bak';    
GO