
USE OFIRECA
GO
DBCC DBREINDEX ( 'TCCOBR',XPKTCCOBR,80);
DBCC DBREINDEX ( 'TCCOBR',ITTCCOBR_0001,80);
DBCC DBREINDEX ( 'TDCOBR_DOCU',XPKTDCOBR_DOCU,80);
DBCC DBREINDEX ( 'TDCOBR_DOCU',IXTDCOBR_DOCU,80);
DBCC DBREINDEX ( 'TDCOBR_TCOB',XPKTDCOBR_TCOB,80);
DBCC DBREINDEX ( 'TDCOBR_TCOB',IXTDCOBR_TCOB_I01,80);
DBCC DBREINDEX ( 'TDCOBR_TCOB_DOCU',XPKTDCOBR_TCOB_DOCU,80);
DBCC DBREINDEX ( 'TDCOBR_TCOB_DOCU',ITTDCOBR_TCOB_DOCU_0001,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',XPKTCDOCU_CLIE,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',ICDOCU_CLIE_1,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',ICDOCU_CLIE_2,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',ICDOCU_CLIE_3,80);
DBCC DBREINDEX ( 'TDDOCU_CLIE',XPKTDDOCU_CLIE,80);
DBCC DBREINDEX ( 'TDDOCU_CCTR',XPKTDDOCU_CCTR,80);
DBCC DBREINDEX ( 'TMCLIE',XPKTMCLIE,80);


/*
USE VENTAS
GO
DBCC DBREINDEX ( 'TCDOCU_CLIE',XPKTCDOCU_CLIE,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',ICDOCU_CLIE_1,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',ICDOCU_CLIE_2,80);
DBCC DBREINDEX ( 'TCDOCU_CLIE',ICDOCU_CLIE_3,80);
DBCC DBREINDEX ( 'TDDOCU_CLIE',XPKTDDOCU_CLIE,80);
DBCC DBREINDEX ( 'TMCLIE',XPKTMCLIE,80);
*/


USE OFILOGI
GO
DBCC DBREINDEX ( 'TMITEM',XPKTMITEM,80);
DBCC DBREINDEX ( 'TMITEM',ITMITEM_01,80);

DBCC DBREINDEX ( 'TMPROV',XPKTMPROV,80);

DBCC DBREINDEX ( 'TCPEDI',XPKTCPEDI,80);
DBCC DBREINDEX ( 'TDPEDI',XPKTDPEDI,80);

DBCC DBREINDEX ( 'TCORDE_COMP',XPKTCORDE_COMP,80);
DBCC DBREINDEX ( 'TDORDE_COMP',XPKTDORDE_COMP,80);

DBCC DBREINDEX ( 'TCDOCU_ALMA',XPKTCDOCU_ALMA,80);
DBCC DBREINDEX ( 'TCDOCU_ALMA',ITCDOCU_ALMA_01,80);
DBCC DBREINDEX ( 'TCDOCU_ALMA',ITCDOCU_ALMA_02,80);
DBCC DBREINDEX ( 'TCDOCU_ALMA',ITCDOCU_ALMA_03,80);
DBCC DBREINDEX ( 'TCDOCU_ALMA',ITCDOCU_ALMA_04,80);
DBCC DBREINDEX ( 'TCDOCU_ALMA',ITCDOCU_ALMA_05,80);

DBCC DBREINDEX ( 'TDDOCU_ALMA',XPKTDDOCU_ALMA,80);
DBCC DBREINDEX ( 'TDDOCU_ALMA',ITDDOCU_ALMA_01,80);
DBCC DBREINDEX ( 'TDDOCU_ALMA',ITDDOCU_ALMA_02,80);
DBCC DBREINDEX ( 'TDDOCU_ALMA',ITDDOCU_ALMA_03,80);
DBCC DBREINDEX ( 'TDDOCU_ALMA',ITDDOCU_ALMA_04,80);
DBCC DBREINDEX ( 'TDDOCU_ALMA',ITDDOCU_ALMA_05,80);

DBCC DBREINDEX ( 'TASTOC_ACTU',XPKTASTOC_ACTU,80);
DBCC DBREINDEX ( 'TASTOC_ACTU',ITASTOC_ACTU_01,80);

DBCC DBREINDEX ( 'TASTAC_MENS',XPKTASTAC_MENS,80);
DBCC DBREINDEX ( 'TASTAC_MENS',ITASTAC_MENS_01,80);
DBCC DBREINDEX ( 'TASTAC_MENS',ITASTAC_MENS_02,80);
DBCC DBREINDEX ( 'TASTAC_MENS',ITASTAC_MENS_03,80);
DBCC DBREINDEX ( 'TASTAC_MENS',ITASTAC_MENS_04,80);

DBCC DBREINDEX ( 'TDITEM_CPRO',XPKTDITEM_CPRO,80);

USE OFICONT
GO

DBCC DBREINDEX ( 'TASALD_EMPR',ITASALD_EMPR_01,80);
DBCC DBREINDEX ( 'TASALD_EMPR',ITASALD_EMPR_02,80);
DBCC DBREINDEX ( 'TASALD_EMPR',ITASALD_EMPR_03,80);
DBCC DBREINDEX ( 'TASALD_EMPR',ITASALD_EMPR_04,80);
DBCC DBREINDEX ( 'TASALD_EMPR',ITASALD_EMPR_05,80);

DBCC DBREINDEX ( 'TXMVTO_CNTB',PK_TXMVTO_CNTB_01,80);
DBCC DBREINDEX ( 'TXMVTO_CNTB',ITXMVTO_CNTB_01,80);
DBCC DBREINDEX ( 'TXMVTO_CNTB',ITXMVTO_CNTB_02,80);
DBCC DBREINDEX ( 'TXMVTO_CNTB',ITXMVTO_CNTB_03,80);
DBCC DBREINDEX ( 'TXMVTO_CNTB',ITXMVTO_CNTB_04,80);
DBCC DBREINDEX ( 'TXMVTO_CNTB',ITXMVTO_CNTB_05,80);
DBCC DBREINDEX ( 'TXMVTO_CNTB',ITXMVTO_CNTB_06,80);

DBCC DBREINDEX ( 'TMOPRC_CNTB',TMOPRC_CNT_17586293081,80);

DBCC DBREINDEX ( 'TCFECH_PROC',TCFECH_PRO_21002025321,80);

DBCC DBREINDEX ( 'TMPLAN_ANNO',TMPLAN_ANNO_18546296501,80);


USE OFITESO
GO

DBCC DBREINDEX ( 'Tdmovi_banc',PK__TDMOVI_BANC__446BDB6B,80);
DBCC DBREINDEX ( 'Tdmovi_banc',ITDMOVI_BANC_01,80);

DBCC DBREINDEX ( 'tdbanc_dist',PK__TDBANC_DIST__1A75A19F,80);

DBCC DBREINDEX ( 'tcmovi_caja',PK__TCMOVI_CAJA__03923C47,80);
DBCC DBREINDEX ( 'tcmovi_caja',ITTCMOVI_CAJA_0001,80);
DBCC DBREINDEX ( 'tcmovi_caja',ITTCMOVI_CAJA_0002,80);

DBCC DBREINDEX ( 'tdmovi_caja',PK__TDMOVI_CAJA__455FFFA4,80);
DBCC DBREINDEX ( 'tdmovi_caja',ITDMOVI_CAJA_01,80);

DBCC DBREINDEX ( 'tdcaja_dist',PK__TDCAJA_DIST__1E463283,80);

DBCC DBREINDEX ( 'tmdocu_prov',PK__TMDOCU_PROV__5F1FD1A7,80);
DBCC DBREINDEX ( 'tmdocu_prov',ITMDOCU_PROV_01,80);

DBCC DBREINDEX ( 'tddisp_ccos',PK__TDDISP_CCOS__38FA28BF,80);

DBCC DBREINDEX ( 'tmdocu_clie',PK__TMDOCU_CLIE__5C4364FC,80);
DBCC DBREINDEX ( 'tmdocu_clie',AK_TMDOCU_CLIE_01,80);
DBCC DBREINDEX ( 'tmdocu_clie',IDTMDOCU_CLIE_I01,80);

DBCC DBREINDEX ( 'tddisc_ccos',PK__TDDISC_CCOS__3711E04D,80);

OFIPRES_OLAP_2010

