--// EN EL SERVIDOR CALW12SQLCORP
--PONER FUERA DE LINEA

ALTER DATABASE NPT53_BALANZA SET OFFLINE
ALTER DATABASE NPT53_NT_WEB SET OFFLINE
ALTER DATABASE NPT53_OCEANO SET OFFLINE
ALTER DATABASE NPT53_PAITA SET OFFLINE


/*

-- PARA ROLLBACK --
-- VOLVER A PONER EN LINEA

ALTER DATABASE NPT53_BALANZA SET ONLINE
ALTER DATABASE NPT53_NT_WEB SET ONLINE
ALTER DATABASE NPT53_OCEANO SET ONLINE
ALTER DATABASE NPT53_PAITA SET ONLINE

*/

--*******************************************************************************************************************************--

--// EN EL SERVIDOR CALW3BDLOG
--PONER FUERA DE LINEA


ALTER DATABASE TritonWeb SET OFFLINE

/*

-- PARA ROLLBACK --
-- VOLVER A PONER EN LINEA

ALTER DATABASE TritonWeb SET ONLINE
*/

--*******************************************************************************************************************************--
--// EN EL SERVIDOR CALW3BPOR
--PONER FUERA DE LINEA

ALTER DATABASE NextelGps SET OFFLINE

/*
-- PARA ROLLBACK --
-- VOLVER A PONER EN LINEA

ALTER DATABASE NextelGps SET ONLINE
*/