--CONSULTA DE ESTADO
SELECT DATABASEPROPERTYEX('NEP_MSCRM_BDI', 'RECOVERY')

DBCC UPDATEUSAGE (NEP_MSCRM_BDI)
SP_SPACEUSED
DBCC SQLPERF(LOGSPACE)


--EJECUTAR REDUCCION
ALTER DATABASE Neptunia_MSCRM SET RECOVERY SIMPLE

USE [Neptunia_MSCRM]
GO
DBCC SHRINKFILE (N'mscrm' , 98088)
GO


