SELECT T2.NU_SOLI_SECU, 
ISNULL(MAX(ISNULL(T7.TI_APRO,'')),'') AS TI_APRO, 
ISNULL(MAX(ISNULL(T1.CO_APRO,'')),'') AS CO_APRO, 
ISNULL(MAX(ISNULL(T7.DE_APRO,'')),'') AS DE_APRO, 
ISNULL(MAX(ISNULL(T2.NU_PASO,'')),'') AS NU_PASO, 
ISNULL(MAX(ISNULL(T5.DE_NOMB_CORT,'')),'') AS DE_NOMB_CORT, 
ISNULL(MAX(ISNULL(T1.FE_USUA_MODI,'')),'') AS FE_CREA_SOLI, 
case ISNULL(MAX(ISNULL(T7.TI_APRO,'')),'') 
when '002' then 'SOLICITUD VACACIONES' 
when '004' then 'MODIF. PRESUPUESTO' 
else ISNULL(MAX(ISNULL(T1.NU_DOCU,'')),'') 
end as NU_DOCU, 
ISNULL(MAX(ISNULL(T1.FE_DOCU,'')),'') AS FE_DOCU, 
ISNULL(MAX(ISNULL(T1.UN_MEDI,'')),'') AS UN_MEDI, 
ISNULL(MAX(ISNULL(T8.DE_MONE,'')),'') AS DE_MONE, 
ISNULL(MAX(ISNULL(T1.ST_SOLI,'')),'') AS ST_SOLI, 
ISNULL(MAX(ISNULL(T1.CO_AUXI_EMPR,'')),'') AS CO_AUXI_EMPR, 
ISNULL(MAX(ISNULL(T6.NO_AUXI,'')),'') AS NO_AUXI, 
ISNULL(MAX(ISNULL(T1.DE_CLAV,'')),'') AS DE_CLAV, 
ISNULL(MAX(ISNULL(T1.FE_STAT_SOLI,'')),'') AS FE_STAT_SOLI, 
ISNULL(MAX(ISNULL(T1.IM_MONT,0)),0) AS IM_MONT 
FROM TCSOLI_APRO T1 
inner join TDSOLI_APRO T2 
on (T1.NU_SOLI_SECU=T2.NU_SOLI_SECU) left outer join TMEMPR T5 on (T1.CO_EMPR=T5.CO_EMPR) 
left outer join TMAUXI T6 
on (T1.CO_EMPR = T6.CO_EMPR AND T1.TI_AUXI_EMPR = T6.TI_AUXI_EMPR AND T1.CO_AUXI_EMPR = T6.CO_AUXI_EMPR) 
left outer join TTTIPO_APRO T7 
on (T1.CO_APRO= T7.CO_APRO) 
left outer join TTUNID_MONE T8 
on (T1.UN_MEDI= T8.CO_MONE), 
	(Select t9.NU_SOLI_SECU, t9.CO_EMPR, t9.CO_APRO, 
		MAX(t9.NU_SECU_PASO) NU_SECU_PASO,  
		MAX(t9.NU_PASO) NU_PASO  
		From TDSOLI_APRO t9  
		Group by t9.NU_SOLI_SECU, t9.CO_EMPR, t9.CO_APRO) t10 
		WHERE 1=1	AND T1.CO_EMPR='01' 
					AND T2.CO_USUA='JMGARCIA' 
		GROUP BY t2.NU_SOLI_SECU 
		ORDER BY t2.NU_SOLI_SECU 