-- Para buscar tablas en una Base de Datos 

-- SQL Server 2000 
SELECT  SYSOBJECTS.NAME AS TABLA, SYSCOLUMNS.NAME AS COLUMNA
FROM SYSOBJECTS 
 INNER JOIN SYSCOLUMNS 
 ON SYSOBJECTS.ID = SYSCOLUMNS.ID 
WHERE SYSOBJECTS.XTYPE IN ('U', 'S')
AND SYSOBJECTS.NAME LIKE '%NOMBRE_TABLA%'
ORDER BY SYSOBJECTS.NAME

   
 --SQL Server 2008
SELECT TABLE_CATALOG AS [BASE DE DATOS], TABLE_NAME AS [TABLA], 
TABLE_TYPE AS [TIPO DE TABLA] 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%NOMBRE_TABLA%'


 