DECLARE @NUMFACTURA NVARCHAR(15)                                                      
DECLARE @TIPMONEDA NVARCHAR(3)                                   
DECLARE @RUCCODIGO NVARCHAR(11)
DECLARE @PARAM INT
DECLARE @REFACTURA INT

SET @NUMFACTURA = 'F115-0000010446'
SET @TIPMONEDA  = 'DOL'
SET @RUCCODIGO  = '20601691621'
SET @PARAM  	= '2'
SET @REFACTURA  = '2'


 SELECT Max(CABDOC.CO_CLIE) RUCCODIGO,
            CABDOC.NU_DOCU NUMDOCCOMPLETO,
        SUM(Convert(int,DETDOC.CA_DOCU)) CANTIDADSERVICIO,
        SERV.DE_SERV NOMSERVICIOOFISIS,
        UNEG.DE_UNNE NOMUNIDADNEGOCIO,
        TIEN.DE_TIEN NOMLOCALTIENDA,
          SUM(DETDOC.IM_TOTA_DETA) TOTALPORLINEA, --Esta es sin IGV
          SUM(DETDOC.IM_TOTA_DETA) MONTODEVOLVER, --Este es el Monto Correcto
          CASE @Refactura WHEN 1 THEN 0 ELSE SUM(DETDOC.IM_TOTA_DETA) END MONTOCORRECTODEVOLVER, --Este es el Monto a Devolver  --'S' AFECTOIMP1,--MAX(DETDOC.ST_IMP1) AFECTOIMP1,  GOS(YQM) Modificado por error en el OFISIS
          CASE WHEN SUM(CABDOC.IM_BRUT_AFEC) > 0 THEN 'S' ELSE 'N' END AFECTOIMP1,
		  CASE WHEN MAX(CABDOC.FE_DOCU) >= '20110301' THEN MAX(CABDOC.PC_IMP1) ELSE 19 END IMPUESTO1, --MAX(CABDOC.PC_IMP1) IMPUESTO1,
          CASE @Refactura WHEN 1 THEN 0
				ELSE  CASE MAX(DETDOC.ST_IMP1) WHEN 'N' THEN SUM(DETDOC.IM_TOTA_DETA) + MAX(CABDOC.PC_IMP1) * SUM(DETDOC.IM_TOTA_DETA)/100 --SUM(DETDOC.IM_TOTA_DETA)--GOS(YQM) Modificado por Error en OFISIS
						ELSE SUM(DETDOC.IM_TOTA_DETA) + MAX(CABDOC.PC_IMP1) * SUM(DETDOC.IM_TOTA_DETA)/100 END 
		  END MONTOCORRECTODEVOLVERIGV
   FROM	 [COSMOS-DB].OFIRECA.dbo.TDDOCU_CLIE			AS DETDOC
         INNER JOIN [COSMOS-DB].OFIRECA.dbo.TCDOCU_CLIE AS CABDOC
			 ON	(CABDOC.NU_DOCU = DETDOC.NU_DOCU ) and                                                            
				(CABDOC.TI_DOCU = DETDOC.TI_DOCU ) and                                                            
				(CABDOC.CO_UNID = DETDOC.CO_UNID ) and                                                            
				(CABDOC.CO_EMPR = DETDOC.CO_EMPR )  
         INNER JOIN [COSMOS-DB].OFIRECA.dbo.TTSERV		AS SERV
			 ON		(DETDOC.CO_EMPR = SERV.CO_EMPR)                            
				AND (DETDOC.CO_SERV = SERV.CO_SERV) 
         INNER JOIN [COSMOS-DB].OFIRECA.dbo.TTUNID_NEGO	AS UNEG 
			 ON		(DETDOC.CO_EMPR = UNEG.CO_EMPR)                                          
				AND (DETDOC.CO_UNNE = UNEG.CO_UNNE)
         INNER JOIN [COSMOS-DB].OFIRECA.dbo.TMTIEN		AS TIEN
			 ON		(DETDOC.CO_EMPR = TIEN.CO_EMPR)                                  
				AND (DETDOC.CO_TIEN = TIEN.CO_TIEN)                                  
 WHERE		 CABDOC.CO_EMPR = '16'
		 AND CABDOC.TI_DOCU = 'FAC'
         AND(CABDOC.CO_ESTA_DOCU = 'ACT' OR CABDOC.CO_ESTA_DOCU = 'PAG')
         AND CABDOC.NU_DOCU  like '%' + @NUMFACTURA
         AND CABDOC.CO_MONE = @TIPMONEDA
         AND CABDOC.CO_CLIE = @RUCCODIGO
         AND TIEN.DE_TIEN <>  'OLI PLUSPETROL'
GROUP BY	CABDOC.TI_DOCU,
			CABDOC.NU_DOCU,
			DETDOC.CO_SERV, 
			DETDOC.CO_UNNE, 
			DETDOC.CO_TIEN,
			SERV.DE_SERV,
			UNEG.DE_UNNE,
			TIEN.DE_TIEN
--ORDER BY TTSERV.DE_SERV  
