
-- INFORMATIVAS                  --DE VALIDACION
DBCC INPUTBUFFER                 DBCC CHECKALLOC
DBCC OPENTRAN                    DBCC CHECKCATALOG
DBCC OUTPUTBUFFER                DBCC CHECKCONSTRAINTS
DBCC PROCCACHE                   DBCC CHECKDB
DBCC SHOW_STATISTICS             DBCC CHECKFILEGROUP
DBCC SHOWCONTIG                  DBCC CHECKIDENT
DBCC SQLPERF                     DBCC CHECKTABLE
DBCC TRACESTATUS
DBCC USEROPTIONS


--DE MANTENIMIENTO                -- OTRAS VARIAS...
DBCC CLEANTABLE                   DBCC dllname (FREE)
DBCC DBREINDEX                    DBCC FREESESSIONCACHE
DBCC DROPCLEANBUFFERS             DBCC FREESYSTEMCACHE
DBCC FREEPROCCACHE                DBCC HELP
DBCC INDEXDEFRAG                  DBCC TRACEOFF
DBCC SHRINKDATABASE               DBCC TRACEON
DBCC SHRINKFILE
DBCC UPDATEUSAGE

-- VARIABLES
select @@CURSOR_ROWS
Select @@Language
Select @@Version
Select @@Servername


Select @@CPU_BUSY                SELECT @@CPU_BUSY * CAST(@@TIMETICKS AS float) AS 'CPU microseconds', 
Select @@TIMETICKS               GETDATE() AS 'As of' ;
Select @@IO_BUSY
Select @@IDLE

Select @@ERROR



