sqlcmd -S NEPTUNIA1 	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S NEPTUNIA2 	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S OCEANICA1 	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3MAP003   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW8BDSCOT   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3OTBDTST  -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S FACTNPT       -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3IDXWMS   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDLOG    -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDPOR    -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDCRM   	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDWMS001 -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDCRM002 -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDWCF001 -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3PNT002   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3BDSGC2   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3ERP001   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3ERP002   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW3ISO001   -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW12SQLCORP -i D:\PASEPRO_MS\MANTI002.sql


sqlcmd -S CALW8BDSOLPORT	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW12BDSOLPORT 	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW12BDALMAF    	-i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW12BDWMS001    -i D:\PASEPRO_MS\MANTI002.sql
sqlcmd -S CALW12BDALMAF    	-i D:\PASEPRO_MS\MANTI002.sql


PAUSE
