select 
A.CO_CLIE,
(SELECT NO_CLIE FROM TMCLIE WHERE CO_EMPR = '01' AND CO_CLIE = A.CO_CLIE) AS NO_CLIE,
A.CO_TIPO_DOCU,
A.NU_DOCU_CLIE,
A.FE_EMIS,
A.CO_COND_PAGO,
A.CO_MONE,
A.FA_TIPO_CAMB,
B.NU_SECU,
B.CO_SERV,
(SELECT DE_SERV FROM TTSERV WHERE CO_EMPR = '01' AND CO_SERV = B.CO_SERV) AS DE_SERV,
B.CO_TIPO_CCTR,
(SELECT DE_TIPO_CCTR FROM TTTIPO_CCTR WHERE CO_TIPO_CCTR = B.CO_TIPO_CCTR) AS DE_TIPO_CCTR,
B.CO_TAMA_CCTR,
(SELECT DE_TAMA_CCTR FROM TTTAMA_CCTR WHERE CO_TAMA_CCTR = B.CO_TAMA_CCTR) AS DE_TAMA_CCTR,
B.CO_COND_CCTR,
(SELECT DE_COND_CCTR FROM TTCOND_CCTR WHERE CO_COND_CCTR = B.CO_COND_CCTR) AS DE_COND_CCTR,
B.CA_DOCU,
B.PR_VENT,
B.IM_TOTA_DETA,
B.CO_NAVE_VIAJ,
B.DE_OBSE_0001 AS DE_OBSE_DET,
A.IM_BRUT_AFEC,
A.IM_BRUT_INAF,
A.IM_IMP1,
A.IM_TOTA,
A.DE_OBSE_0001 AS DE_OBSE_CABE,
(SELECT DE_NAVE_VIAJ FROM TTNAVE_VIAJ WHERE CO_EMPR = '01' AND CO_NAVE_VIAJ = B.CO_NAVE_VIAJ  AND CO_UNID = B.CO_UNID) AS DE_NAVE_VIAJ 
from tmdocu_clie A
LEFT JOIN TDDOCU_CLIE B
ON A.CO_EMPR = B.CO_EMPR AND A.CO_TIPO_DOCU = B.TI_DOCU AND A.NU_DOCU_CLIE = B.NU_DOCU AND A.CO_UNID_CONC = B.CO_UNID
WHERE YEAR(FE_EMIS) = 2016

--SELECT * FROM TDDOCU_CLIE

/*
select top 100 *
from tmdocu_clie

select top 100 *
FROM TDDOCU_CLIE

SELECT top 100 * FROM TCDOCU_CLIE_GENE ORDER BY FE_DOCU DESC
*/